houseprint/inventory/models.py
from datetime import datetime
from houseprint import db
import json

class Category(db.Model):
    __tablename__ = "category"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(), unique=True, nullable=False)

    def __repr__(self):
        return f"ID: {self.id}\nName:{self.name}"

class Item(db.Model):
    __tablename__ = "item"
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(), nullable=False)
    barcode = db.Column(db.String(), nullable=False, unique=True)
    category_id = db.Column(db.Integer, db.ForeignKey('category.id'), nullable=False)
    _category = db.relationship('Category', backref='category')

    def __repr__(self):
        return f"{self.name}\n{self.barcode}\n{self._category.name}"

    def payload(self):
        return {
            "id":self.id,
            "name":self.name,
            "barcode":self.barcode,
            "category":self._category.name
        }

class Inventory(db.Model):
    __tablename__= 'inventory'
    id = db.Column(db.Integer, primary_key=True)
    item_id = db.Column(db.Integer, db.ForeignKey('item.id'), nullable=False)
    _item = db.relationship('Item', backref='item', lazy=True)
    quantity = db.Column(db.Integer, nullable=False)

    def __repr__(self):
        return f"{self.id}:{self._item.name}\nInStock:{self.quantity}"

    def payload(self):
        return {
            "id": self.id,
            "name": self._item.name,
            "quantity": self.quantity,
            "barcode": self._item.barcode,
            "category": self._item._category.name
        }

houseprint/inventory/routes.py
from flask import render_template, url_for, flash, redirect, request, jsonify, Blueprint
from houseprint import app, db, bcrypt
from houseprint.users.models import User
from houseprint.inventory.models import Item, Inventory, Category
from flask_login import current_user, login_required
#Error Handlers
from sqlalchemy.exc import IntegrityError
import traceback


inv= Blueprint('inventory', __name__)

#@inv.before_request
#def print_ip():
#    print(request.__dict__)
#    print(request.remote_addr)
#    print(request.environ.get('REMOTE_ADDR', 'ADDR_NOT_FOUND'))

@inv.route("/inventory", methods=["GET", "POST", "PUT"])

def inventory():
    if not current_user.is_authenticated:
        return redirect(url_for('main.home'))
    category = Category.query.all()
    if request.method == 'POST':
        param = request.form.get('search', None)
        if param:
            inventory = Inventory.query.join(Item).filter_by(name=param).paginate(
                page=1, per_page=25)
            title = f"Inventory ~ {param}"
        else:
            return redirect(url_for("inventory.inventory"))

    elif request.method == 'GET':
        #We will pass a list of objects to Jinja. HTML is configured for the objects.
        page = request.args.get('page', 1, type=int)
        inventory = Inventory.query.join(Item).order_by(Item.name.desc())\
            .paginate(page=page, per_page=25)
        title = "Inventory"
        #inventory is a Pagination Object; use .pages & .items
    return render_template("inventory.html", _title=title,
        inventory=inventory.items, pages=inventory.pages, categories=category)

@inv.route("/inventory/_category", methods=["POST","PUT"])
def _category():
    category = request.json['category']
    _c = Category(name=category)
    try:
        db.session.add(_c)
        db.session.commit()
    except IntegrityError:
        db.rollback()
        flash(f'Unique Contraint Error, try renaming {category}')
        return "false"
    except Exception:
        flash(traceback.print_exc())
        return "false"
    finally:
        return category

@inv.route("/inventory/_barcode", methods=["POST","PUT"])
def _barcode():
    barcode = request.json['barcode']
    item = Item.query.filter_by(barcode=barcode).first()
    if item:
        return jsonify(item.payload())
    else:
        return "false"

houseprint/main/routes.py
from flask import render_template, url_for, flash, redirect, request, jsonify, Blueprint
from houseprint import app, db, bcrypt
from houseprint.users.models import User
from flask_login import login_required

main = Blueprint('main', __name__)

@main.route("/", methods=["GET", "POST"])
@main.route("/home", methods=["GET", "POST"])
def home():
    return render_template("index.html", _title="Housemates")


@main.route("/screen", methods=["GET","POST"])
@login_required
def screen():
    return render_template("screen.html")

houseprint/users/routes.py
from flask import render_template, url_for, flash, redirect, request, jsonify, abort, Blueprint
from flask_login import current_user, login_required, login_user, logout_user

from functools import wraps

from houseprint import db, app, bcrypt
from houseprint.users.forms import (LoginForm, RegistrationForm,
    ResetRequestForm, ResetPasswordForm)
from houseprint.users.models import User

user = Blueprint('user', __name__)
"""
The following method is a template for checking a potential users IP address
against trust IP addresses in a seperate database. This database will also
be used to check a user's permissions.
-DB
--Table: AnonApproved {
    id: PK
    user_id: FK U (reference to table)
    ip_addr: U (hashed)
}
--Table: AnonDenied {
    id: PK
    ip_addr: U (hashed)
}
--Table: Users {
    id: PK
    u_id: FK U(refers to seperate db)
}
--Table: Permissions {
    id: PK
    u_id: FK U (refers to table)
    rule_id: U (points to json file, static files)
}
"""
#def check_ip_addr():
#    @wraps(app.before_request)
#
#    def _check_ip_addr(*args, **kwargs):
#        ip_addr = request.environ.get('REMOTE_ADDR', request.remote_addr)
#        if AnonApproved.query.filter_by(ip_addr=bcrypt.check_password_hash(ip_addr)).first():
#            flash(f"{ip_addr} approved! Welcome.")
#            return
#        else:
#            abort(404)


@user.route("/user/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email = form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember = form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash("Login unsuccessful, check credentials.", 'danger')
    return render_template("login.html", form = form)

@user.route('/user/register', methods = ["GET", "POST"])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created. You may now login.', 'success')
        return render_template(url_for("user.login"))
    return render_template('register.html', form=form)

@user.route("/user/reset_password")
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = ResetRequestForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        #INSERT CODE TO SEND EMAIL

        #INSERT CODE TO SEND EMAIL
        flash("An email has been sent with the reset instructions.", 'info')
        return redirect(url_for('user.login'))
    return render_template('reset_request.html', form=form)

@user.route('/user/reset_password/<token>', methods = ["GET", "POST"])
def reset_token():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash("Token is invalid or expired.", 'warning')
        return redirect(url_for('user.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flash("Password updated successfully.", 'success')
        return redirect(url_for('user.login'))
    return render_template('reset_token.html', form=form)

@user.route('/user/logout', methods=["GET", "POST"])
def logout():
    logout_user()
    return redirect(url_for('main.home'))

houseprint/templates/__baselayout.html
<!--Use Jinja to dynamically add the content delivered; special documents displayed will be in iFrames-->
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{{url_for('static', filename='/css/master.css')}}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
    {% if title %}
      <title>Houseprint - {{ title }}</title>
    {% else %}
      <title>Houseprint</title>
    {% endif %}
    </head>
    <body>
      <!--Navbar for top of page; uses Jinja to insert links based on current page -->
      <nav class="navbar navbar-light bg-steel fixed-top p-0">
        <div class="container-fluid">
          <a href="{{url_for('main.home')}}" class="navbar-brand col-sm-3 col-md-2 mr-0">Housemates</a>
          <button class="auto-end navbar-toggler" style="justify-content:end;"id="navToggler" type="button" name="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="navbarCollapse" style="text-align: end;">
          <ul class="navbar-nav me-auto mb-lg-0">
            {% if current_user.is_authenticated %}
            {%block navbar%}
            {%endblock navbar%}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('user.logout')}}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{ url_for('user.register') }}">Register</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
      <!--Any alerts that are created due to action errors, displayed above all content-->
      <div class="container site-alerts">
        {% with messages = get_flashed_messages('with_categories=true') %}
          {% if messages %}
            {% for category, message in messages %}
              <div class="alert alert-{{ category }}">
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}
        {% endwith %}
      </div>

      <div class="container" style="padding:0;">
        <div class="row justify-flex-end">
          <!-- This is the section for a left-side navigation bar; used for page specific requests -->
          <nav class="col-sm-2 col-md-2 col-lg-2 col-xl-2 d-none d-md-block bg-alum sidebar yhide">
            <div class="sidebar-sticky yhide width100">
              {%block sidebar%}
              {%endblock sidebar%}
            </div>
          </nav>
          <main role="main" class="col-sm-10 col-md-10 col-lg-10 ml-sm-auto ml-md-auto ml-lg-auto col-xl-10 px-4 content" >
            <div class="flexwrap flex-md-nowrap pb-2 mt-0 mb-3 border-bottom" style="justify-content: end;">
              <div class="container-block">
                <div class="bg-blue central-header">
                  {% if _title %}
                    <h1 class="display-6 ms-3 mt-3" ><u class="title-underline">{{_title}}</u></h1>
                  {% else %}
                    <h1 class="display-6 ms-3 mt-3"> <u class="title-underline">Housemates</u> </h1>
                  {% endif %}
                </div>
                <div class="container-flex">
                  {% block content %}{% endblock content %}
                </div>
              </div>
            </div>
          </main>
        </div>
      </div>
      {% block templates %}
      {% endblock templates %}

      <div id="modalBase" role="dialog" class="modal fade">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header bg-blue hstack gap-0">
              <h1 class="display 6">
                <u class="title-underline" id="modalTitle"></u>
              </h1>
                <button type="button" class="btn-close btn-outline-danger top-0 end-0" onclick = "clearModal()" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">
              <div id="modalBody">

              </div>
            </div>
          </div>
        </div>
      </div>
    </body>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" crossorigin="anonymous"></script>

    <!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>-->

    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
        <script>
          feather.replace();
        </script>
        
    <script type="text/javascript">

      $(document).ready(function(e){
        $(document).on('click', function(f){
          $("#navbarCollapse").collapse('hide');
        })
      })

      function showModal(body, title){
        $("#modalBody").append(body);
        $("#modalTitle").html(title);
        $("#modalBase").modal('show');
      }

      function clearModal(){
        setTimeout(function(e){
          $("#modalBody").html("");
          $("#modalBase").modal('hide');
        }, 3);
      }

    </script>
    {% block scripts %}
    {% endblock scripts %}
</html>

houseprint/templates/index.html
{% extends "__baselayout.html" %}
{% block navbar %}
  <li class="nav-item">
    <a class="nav-link" href="{{ url_for('inventory.inventory')}}">Inventory</a>
  </li>
{% endblock navbar %}

houseprint/templates/inventory.html
{% extends "__baselayout.html" %}
{% block navbar %}
<li class="nav-item">
  <a class="nav-link" href="{{url_for('main.screen')}}">Screen</a>
</li>
{% endblock navbar %}

{% block sidebar %}
<ul class="nav flex-column justify-content-between align-items-center">
  <li class="nav-item">
    <!--Here we have the SCAN BARCODE element just a few pixels offset from the rest. Look for fix in future-->
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center d-flex mt-4 mb-1 text-muted">
      <span>Scan Barcode</span>
      <button type="button" name="button" class="btn d-flex text-muted" onclick="scanBarcodeTemplate()">
        <span data-feather="align-right" style="transform: rotate(90deg);"></span>
      </button>
    </h6>
  </li>
  <li class="nav-item">
    <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-1 mt-1 mb-1 text-muted">
      <span>Search</span>
      <button type="submit" name="SEARCH" id="searchSubmit" class="btn d-flex text-muted" form="searchForm">
        <span data-feather="search"></span>
      </button>
    </h6>

    <form class="d-flex text-muted" id="searchForm" action="{{url_for('inventory.inventory')}}" method="post">
      <fieldset class="form-group">
        <input type="hidden" name="csrf_token" value="{{ csrf_token () }}">
        <div class="form-group px-1">
          <input class="form-control" type="text" name="search" id="searchInput" value="" placeholder="Search">
        </div>
      </fieldset>
    </form>
  </li>
</ul>

<h6 class="sidebar-heading d-flex justify-content-between align-items-center px-1 mt-2 mb-1 text-muted">
  <span>Categories</span>
  <button type="button" name="button" class="btn d-flex text-muted" onclick="categoryPushTemplate()">
    <span data-feather="plus-circle"></span>
  </button>
</h6>
<ul id="categoryList" class="nav flex-column mb-2 justify-content-between align-items-center">
  {% for category in categories %}
    <li class="nav-item">
      <a href="" class="nav-link" onclick="return categoryInventory('{{category.name}}')">{{category.name}}</a>
    </li>
  {% endfor %}
</ul>
{% endblock sidebar %}

{% block content %}
  <div class="y-scroll">
    <table class="table table-hover y-scroll">
      <thead>
        <tr>
          <th>Item ID</th>
          <th>Name</th>
          <th>Quantity</th>
          <th>Update</th>
        </tr>
      </thead>
      <tbody id="inventoryBody">
        {% for item in inventory %}
        <!--index is offset due to SQL base 1 indexing-->
        {% set index = item.id - 1 %}
          <tr>
            <td>{{item.id}}</td>
            <td>{{item._item.name}}</td>
            <td>{{item.quantity}}</td>
            <td>
              <button type="button" class="btn btn-info btn-sm" onclick="itemUpdate('{{index}}')" name="button">Update</button>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock content %}

{% block templates %}
<!--templates are found by arr.filter() on the template's ID-->
<template id="categoryPushForm">
  <div class="container">
    <form class="form" action="" method="post">
      <fieldset class='form-group'>
        <div class="form-group">
          <input type="text" name="categoryNameInput" id="categoryNameInput" value="" placeholder="Enter category name.">
        </div>
      </fieldset>
    </form>
    <div class="container-fluid justify-content-end align-items-end">
      <button type="button" name="categorySubmit" onclick="categoryPush()" class="btn btn-md btn-success">Submit</button>
      <button type="button" name="categoryCancel" onclick="clearModal()" class="btn btn-md btn-danger">Cancel</button>
    </div>
  </div>
</template>

<template id="sidebarRowTemplate">
  <li class="nav-item">
    <a href="" id="sidebarRow" class="nav-link"></a>
  </li>
</template>

<template id="barcodeScanTemplate">
  <div class="container">
    <form method="post">
      <fieldset class="form-group">
        <input type="hidden" name="csrf_token" value="{{csrf_token()}}">
        <div class="form-group">
          <input class="form-control d-flex text-muted" type="text" id="barcodeInput" name="barcodeInput" value="" placeholder="Scan Item, Press 'Enter' if necessary">
        </div>
      </fieldset>
    </form>
    <div id="itemRoster" class="container vstack d-flex justify-content-between align-items-center mt-2 y-scroll yhide" style="max-height:calc(100vh * .65);">

    </div>
    <div class="horizontal-line"></div>
    <div class="d-flex" style="float:right;">
      <button class="btn btn-success px-3 mx-2" type="button" name="barcodeSubmit" onclick="barcodePush()">Submit</button>
      <button class="btn btn-danger px-3 mx-2" type="button" name="barcodeCancel" onclick="clearModal()">Cancel</button>
    </div>
  </div>
</template>

<template id="itemTemplate">
  <div class="card mb-1 mt-1 width100">
    <div class="card-header" id="itemIsFound">

    </div>
    <div class="table-responsive">
      <table class="table table-sm">
        <thead>
          <tr>
            <th>Item Name:</th>
            <th>Barcode:</th>
            <th>Category:</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td id="itemName"></td>
            <td id="itemBarcode"></td>
            <td id="itemCategory"></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>
{% endblock templates %}

{% block modal %}

{% endblock modal %}

{% block scripts %}
<!--Icon package-->

<script type="text/javascript">
      var dataWrapper = {
        csrf:"{{csrf_token()}}",
        scriptRoot: {{ request.script_root|tojson|safe }}
      }
    </script>

<script type="text/javascript">
  function categoryInventory(category){
    alert(category);
    return false
  };
  function searchInventory(){
    let x = document.getElementById("#searchForm")
    x.submit();
    /*window.location.reload(true);*/
    return false;
  };
/*
  function searchInventory(){
    let searchParam = $("#searchInput").val()
    let xhr = new XMLHttpRequest();
    xhr.open('POST', '{{url_for("inventory.inventory")}}')
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.setRequestHeader('X-CSRFToken', dataWrapper.csrf);
    xhr.onload = function() {
      if (xhr.status === 200) {
        alert('Success')
      } else if (xhr.status !== 200){
        alert('Failure:' + xhr.status)
      };
    };
    xhr.send(JSON.stringify({
      search:searchParam
    }));
    return true;
  };
*/
/*
*Modal Populators
*If created via <a>-tag you will need to return false to prevent page-wandering
*Use of AJAX to push data updates to server
*/
  function categoryPushTemplate(){
    /*Necessary in case of template ordering errors and bugs; can't use index*/
    let catArray = [].slice.call(document.getElementsByTagName("template"));
    let _ = catArray.filter(function e(idx) {
      return idx.id === "categoryPushForm"
    });
    let newForm = _[0].content.firstElementChild.cloneNode(true);
    showModal(newForm, "Add Category")
    return false;
  };

  function categoryPush(){
    let formData = $("#categoryNameInput").val()
    let xhr = new XMLHttpRequest();
    xhr.open('PUT', '{{url_for("inventory._category")}}');
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.setRequestHeader('X-CSRFToken', dataWrapper.csrf);
    xhr.onload = function() {
      if (xhr.status === 200 && xhr.responseText !== formData) {
        alert('Something went wrong.' + xhr.responseText)
      } else if (xhr.status !== 200) {
        alert("Request failed. Status code:" + xhr.status);
      } else if (xhr.status === 200 && xhr.responseText === formData){
        clearModal();
        updateSidebar(formData);
      };
    };
    xhr.send(JSON.stringify({
      category:formData
    }));
    return false;
  };


  function updateSidebar(category){
    let arr = [].slice.call(document.getElementsByTagName("template"))
    let row = arr.filter(function (e){return e.id === "sidebarRowTemplate"});
    let newRow = row[0].content.firstElementChild.cloneNode(true);
    $("#categoryList").append(newRow);
    $(newRow).find("#sidebarRow").text(category);
    /*This has got to be incorrect*/
    $(newRow).find("#sidebarRow").on('click', function(){return categoryInventory(category);})
    console.log($(newRow).find("#sidebarRow"));
    return false;
  };

  function scanBarcodeTemplate(){
    let arr = [].slice.call(document.getElementsByTagName("template"))
    let temp = arr.filter(function (e){return e.id === "barcodeScanTemplate"});
    let newTemp = temp[0].content.firstElementChild.cloneNode(true);
    showModal(newTemp, "Scan Items");
    /*This may be messy, it will reference template elements after
    *they're created. There might be room for error within it.
    */
    barcodeConfig();
    return false;
  };

  function itemCardTemplate(data, isKnown){
    let arr = [].slice.call(document.getElementsByTagName("template"));
    let temp = arr.filter(function (e){return e.id === "itemTemplate"});
    let newTemp = temp[0].content.firstElementChild.cloneNode(true);
    newTemp.querySelector("#itemIsFound").textContent = "Item Not Found";
    newTemp.querySelector("#itemBarcode").textContent = data['barcode']
    document.querySelector("#itemRoster").appendChild(newTemp);
    return false;
  };

  function barcodeConfig(){
    /*
    *Here we have the configuration to block the form from
    *being submitted. Instead an XMLHttpRequest is sent
    *and our program will create cards based on the result.
    *'false' result indicates Item not found, otherwise
    *a JSON object will be passed with Name, Category, and Stock
    */
    let el = document.querySelector("#barcodeInput");
    el.addEventListener('keypress', function(e) {
      if (e.key === 'Enter') {
        e.preventDefault();
        barcodePush();
      };
    });
    return false;
  };

  function barcodePush(){
    let formData = $("#barcodeInput").val();
    /* information we can reasonably expect to receive */
    let itemData = {
      barcode: formData,
      name: null,
      category: null,
      quantity: null
    };
    Object.keys(itemData).forEach(function(key, idx) {
      console.log(key);
      console.log(itemData[key])
    });
    let xhr = new XMLHttpRequest();
    xhr.open('PUT', '{{url_for("inventory._barcode")}}');
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.setRequestHeader('X-CSRFToken', dataWrapper.csrf)
    xhr.onload = function() {
      if (xhr.status === 200 && xhr.responseText !== formData) {
        /*Item not found in database xhr.responseText is "false"*/
        itemCardTemplate(itemData, false);
      } else if (xhr.status !== 200) {
        /*Error here means either route changed or service is non-operational*/
        alert('Request failed. Status code:' + xhr.status);
      } else if (xhr.status === 200 && xhr.responseText === formData){
        /*Item found in database response containse JSON data*/
        let obj = JSON.parse(xhr.responseText);

        Object.keys(obj).forEach(function(key, idx) {
          itemData[key] = obj[key];
        })
      };
      $("#barcodeInput").val('');
    };
    xhr.send(JSON.stringify({
      barcode:formData
    }));
    return false;
  };
</script>
{% endblock scripts %}

houseprint/templates/login.html
{% extends "__baselayout.html" %}
{% block content %}
  <div class="container">
    <form action="" method="post">
      {{form.hidden_tag()}}
      <fieldset class="form-grou">
        <legend class="border-bottom mb-4">Login</legend>
        <div class="form-group">
          {{form.email.label(class="form-control-label")}}
          {% if form.email.errors %}
            {{form.email(class="form-control form-control-lg is-invalid")}}
            <div class="invalid-feedback">
              {% for error in form.email.errors %}
                <span class='is-invalid'>{{error}}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.email(class="form-control form-control-lg")}}
          {% endif %}
        </div>
        <div class="form-group">
          {{form.password.label(class="form-control-label")}}
          {% if form.password.errors %}
            {{ form.password(class="form-control form-control-lg is-invalid")}}
            <div class="invalid-feedback">
              {% for error in form.password.errors %}
                <span class='is-invalid'>{{error}}</span>
              {% endfor %}
            </div>
          {% else %}
            {{ form.password(class="form-control form-control-lg")}}
          {% endif %}
        </div>
        <div class="form-check">
          {{form.remember(class="form-check-input")}}
          {{form.remember.label(class="form-check-label")}}
        </div>
      </fieldset>
      <div class="form-group">
        {{form.submit(class="btn btn-outline-info")}}
      </div>
      <small class="text-muted ml-2"><a href="#">Forgot Password</a></small>
    </form>

  </div>
{% endblock content %}

houseprint/templates/register.html
{% extends "__baselayout.html" %}
{% block content %}
  <div class="content-section">
      <form action="" method="post">
        {{ form.hidden_tag() }}
        <fieldset class='form-group'>
            <legend class='border-bottom mb-4'>Join Today</legend>
            <div class="form-group">
              {{ form.username.label(class="form-control-label") }}

              {% if form.username.errors %}
                {{ form.username(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.username.errors %}
                    <span class= 'is-invalid'>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.username(class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.email.label(class="form-control-label") }}
              {% if form.email.errors %}
                {{ form.email(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.email.errors %}
                    <span class = 'is-invalid'>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.email(class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.password.label(class="form-control-label") }}
              {% if form.password.errors %}
                {{ form.password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.password.errors %}
                    <span class='is-invalid'>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.password(class="form-control form-control-lg") }}
              {% endif %}
            </div>
            <div class="form-group">
              {{ form.confirm_password.label(class="form-control-label") }}
              {% if form.confirm_password.errors %}
                {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                <div class="invalid-feedback">
                  {% for error in form.confirm_password.errors %}
                    <span class='is-invalid'>{{ error }}</span>
                  {% endfor %}
                </div>
              {% else %}
                {{ form.confirm_password(class="form-control form-control-lg") }}
              {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
          {{ form.submit(class="btn btn-outline-info") }}
        </div>
      </form>
  </div>
  <div class="border-top pt-3">
    <small class='text-muted'>
        Already Have An Account? <a class='ml-2' href="{{ url_for('user.login')}}">Login</a>
    </small>

  </div>
{% endblock content %}